import turtle

turtle.pensize(5)
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.circle(200)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.goto (-120,0)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.color("gray")
turtle.goto (140, 0)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.color("red")
turtle.goto(0,160)
turtle.penup()
turtle.color("black")
turtle.pensize(2)
turtle.goto(-5, 180)
turtle.pendown()
turtle.write(12, move=False, align="left", font=("Arial", 12, "normal"))
turtle.penup()
turtle.right(90)
turtle.forward(370)
turtle.write(6, move=False, align="left", font=("Arial", 12, "normal"))
turtle.goto(-180, -5)
turtle.write(9, move=False, align="left", font=("Arial", 12, "normal"))
turtle.right(90)
turtle.goto(180, -5)
turtle.write(3, move=False, align="left", font=("Arial", 12, "normal"))
turtle.goto(-25, -225)
turtle.write("9:15:00", move=False, align="left", font=("Arial", 12, "normal"))

turtle.hideturtle()


