import turtle
turtle.pensize(5)
turtle.penup()
turtle.goto(-200, 0)
turtle.pendown()
turtle.forward(400)
turtle.penup()
turtle.goto(0,200)
turtle.pendown()
turtle.right(90)
turtle.forward (400)
